### PR TITLE
CD-15: Documentation improvements

### PR DESCRIPTION
**Pull request by hanki-kim**
Cleaned up JSDoc documentation

### CODE REVIEW

**Comment by thucngyyen** [comment]
The documentation looks very good! @farnaf are you ok if I merge this pr, are you working on the linting part? Or I will wait until you merge yours?

**Comment by thucngyyen** [comment]
@hanki-kim there is some conflict that need to be solved

**Comment by hanki-kim** [comment]
I can fix them right now!

**Comment by hanki-kim** [comment]
@thucngyyen @farnaf Can you guys review this one more time. Made the changes to the updated file structure

**Comment by thucngyyen** [comment]
Next time, make sure you follow the naming rule on your branch, your branch should be CD-15

**Comment by hanki-kim** [comment]
@thucngyyen @farnaf just merged the changes made by CD-11

**Pull request merged**
